# Generated by Django 3.2.8 on 2021-12-07 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ED', 'Education'), ('JO', 'Job'), ('SE', 'Seminar')], max_length=2)),
                ('title_is', models.CharField(max_length=30)),
                ('title_en', models.CharField(max_length=30)),
                ('where_is', models.CharField(max_length=30)),
                ('where_en', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('leave', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kt', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('intro', models.TextField()),
                ('hobbies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reccommendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('workplace_is', models.CharField(max_length=30)),
                ('workplace_en', models.CharField(max_length=30)),
                ('title_is', models.CharField(max_length=20)),
                ('title_en', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name_is', models.CharField(max_length=15)),
                ('skill_name_en', models.CharField(max_length=15)),
                ('skill_level', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ItemPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_is', models.TextField()),
                ('text_en', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cv.cvitem')),
            ],
        ),
    ]
