# Generated by Django 3.2.14 on 2022-09-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='hobbies',
            new_name='hobbies_en',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='intro',
            new_name='hobbies_is',
        ),
        migrations.AddField(
            model_name='person',
            name='intro_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='intro_is',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
